### ISSUE TITLE
Change exp list to feed from Normandy instead of import job

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/firefox-test-tube#43]
We'll need to show low latency data points for experiments that haven't yet shown up in the nightly import, so we need to get the experiment list from the source.

**Comment by rafrombrc** [comment]
@robhudson Is this resolved now that we're getting real time enrollment numbers from Spark Streaming?

**Comment by robhudson** [comment]
Is this bug about not showing a 404 if the import job for the experiment hasn't run yet? If so, then this isn't completed yet. The enrollment push isn't creating a new experiment record, they are separate, so we would still get a 404 if the import hasn't run yet I'm pretty sure. Unless something was updated on the front-end to check both APIs before deciding to 404.

**Comment by robhudson** [comment]
This is now done.
